# Generated by Django 2.2.9 on 2022-05-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20220513_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(default='', help_text='Напишите название группы', verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(default='', help_text='Напишите название группы', verbose_name='Название'),
        ),
    ]
