# Generated by Django 2.2.16 on 2022-06-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20220515_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(default='', help_text='Напишите описание группы', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(default='', help_text='О чём Вы думаете сейчас?', verbose_name='Сообщение'),
        ),
    ]
